import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { TuiCurrencyPipeModule } from '@taiga-ui/addon-commerce';
import {
	TuiEditorModule,
	TuiEditorSocketModule,
	TuiInputColorModule,
} from '@taiga-ui/addon-editor';
import { TuiSidebarModule } from '@taiga-ui/addon-mobile';
import { TuiPreviewModule } from '@taiga-ui/addon-preview';
import { TuiTableModule } from '@taiga-ui/addon-table';
import { TuiActiveZoneModule, TuiLetModule } from '@taiga-ui/cdk';
import {
	TuiButtonModule,
	TuiDataListModule,
	TuiDialogModule,
	TuiDropdownModule,
	TuiErrorModule,
	TuiExpandModule,
	TuiFormatDatePipeModule,
	TuiFormatNumberPipeModule,
	TuiHintModule,
	TuiHostedDropdownModule,
	TuiLabelModule,
	TuiLinkModule,
	TuiLoaderModule,
	TuiRootModule,
	TuiScrollbarModule,
	TuiSvgModule,
	TuiTextfieldControllerModule,
} from '@taiga-ui/core';
import {
	TuiAccordionModule,
	TuiAvatarModule,
	TuiBadgeModule,
	TuiCarouselModule,
	TuiCheckboxModule,
	TuiComboBoxModule,
	TuiDataListWrapperModule,
	TuiFieldErrorPipeModule,
	TuiFilesModule,
	TuiFilterByInputPipeModule,
	TuiInputCountModule,
	TuiInputDateModule,
	TuiInputFilesModule,
	TuiInputModule,
	TuiInputNumberModule,
	TuiInputPasswordModule,
	TuiInputPhoneModule,
	TuiMarkerIconModule,
	TuiMultiSelectModule,
	TuiPaginationModule,
	TuiProgressModule,
	TuiRadioBlockModule,
	TuiRadioLabeledModule,
	TuiSelectModule,
	TuiStepperModule,
	TuiStringifyPipeModule,
	TuiTabsModule,
	TuiTagModule,
	TuiTextAreaModule,
	TuiToggleModule,
} from '@taiga-ui/kit';

const commonModule = [
	CommonModule,
	TuiRootModule,
	TuiButtonModule,
	TuiLinkModule,
	TuiSvgModule,
	TuiInputModule,
	TuiFieldErrorPipeModule,
	TuiLabelModule,
	TuiTextfieldControllerModule,
	TuiInputPasswordModule,
	TuiHintModule,
	TuiLoaderModule,
	TuiSidebarModule,
	TuiActiveZoneModule,
	TuiHostedDropdownModule,
	TuiDataListModule,
	TuiAccordionModule,
	TuiExpandModule,
	TuiErrorModule,
	TuiAvatarModule,
	TuiRadioLabeledModule,
	TuiInputDateModule,
	TuiDataListModule,
	TuiDropdownModule,
	TuiActiveZoneModule,
	TuiInputPhoneModule,
	TuiProgressModule,
	TuiTabsModule,
	TuiMultiSelectModule,
	TuiDataListWrapperModule,
	TuiInputNumberModule,
	TuiCurrencyPipeModule,
	TuiScrollbarModule,
	TuiTableModule,
	TuiDialogModule,
	TuiFilesModule,
	TuiInputFilesModule,
	TuiSelectModule,
	TuiBadgeModule,
	TuiToggleModule,
	TuiCarouselModule,
	TuiPaginationModule,
	TuiPreviewModule,
	TuiEditorModule,
	TuiTextAreaModule,
	TuiEditorSocketModule,
	TuiLetModule,
	TuiStringifyPipeModule,
	TuiFilterByInputPipeModule,
	TuiFormatNumberPipeModule,
	TuiFormatDatePipeModule,
	TuiInputColorModule,
	TuiCheckboxModule,
	TuiInputCountModule,
	TuiRadioBlockModule,
	TuiTagModule,
	TuiStepperModule,
	TuiComboBoxModule,
	TuiMarkerIconModule,
];

@NgModule({
	imports: [commonModule],
	exports: [commonModule],
})
export class TaigaModule {}
